### ISSUE TITLE
Always fetching data from 127.0.0.1:1337

### ISSUE THREAD

**Issue by sasidharank** [strapi/gatsby-source-strapi#125]
Gatsby always fetching data from localhost also I changed my apiUrl to heroku path.

![Screenshot from 2020-05-11 15-19-44](https://user-images.githubusercontent.com/29498872/81548423-e84f9e00-939a-11ea-9560-d0deeb9a8ed2.png)

**Comment by sasidharank** [comment]
This was fixed by recreating gatsby site. Issue in gatsby cache.

**Comment by alkafaiz** [comment]
Hey @sasidharank  I'm facing the very same issue here. How did u solve it exactly? I've tried deleting gatsby cache with `gatsby clean` but still have the same error. It cannot point to the new apiUrl I specified in `gatsby-config.js` file

**Comment by sasidharank** [comment]
@alkafaiz By recreating the gatsby project. It sounds hard but I tried all ways to solve this issue but creating a new gatsby project and point to hosted apiUrl works.

**Comment by alkafaiz** [comment]
@sasidharank Unfortunately it didnt work for me. May I know what gatsby version u have? mine is 2.22.15

**Comment by sasidharank** [comment]
@alkafaiz the gatsby version is `"gatsby": "^2.21.22"` and   `"gatsby-source-strapi": "0.0.12"`

**Comment by Fredkiss3** [comment]
I had the same problem and i solved it by changing the option **apiUrl** to **apiURL** (U-R-L in capital letters).
