### ISSUE TITLE
Component type is not available inside a dynamic zone 

### ISSUE THREAD

**Issue by tomolenet** [strapi/gatsby-source-strapi#93]
**Describe the bug**
The component type is not accessible inside a dynamic zone.

**Steps to reproduce the behavior**
1. Create content type with a dynamic zone
2. Request the content type by gatsby-source-strapi

**Expected behavior**
Receive the component type of the dynamic zone children to make sure they get rendered properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/38924650/71559075-330af200-2a5a-11ea-903d-6700acbf038c.png)
_Screenshot of gatsby graphql interface. The entry content is the dynamic zone which can contain a text or an image f.e._

![image](https://user-images.githubusercontent.com/38924650/71559101-6fd6e900-2a5a-11ea-8744-cc7d18083a40.png)
![image](https://user-images.githubusercontent.com/38924650/71559107-87ae6d00-2a5a-11ea-8b7b-5b7beadb7c3a.png)

_Screenshots of the dynamic zone in strapi admin interface_

**Code snippets**
```
    "gatsby": "^2.18.14",
    "gatsby-source-filesystem": "^2.1.33",
    "gatsby-source-strapi": "0.0.10",
```
_Gatsby - package.json_

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Gatsby version: 
- Database: MongoDb
- Operating system: Linux

**Comment by tomolenet** [comment]
The `__typename` is available but it always contains the same value.

![image](https://user-images.githubusercontent.com/38924650/71907233-e4e9a300-316b-11ea-84b1-2cb51d256bbb.png)

**Current:**
```
"node": {
  "content": [
    {
      "__typename": "StrapiPostContent"
    },
    {
      "__typename": "StrapiPostContent"
    }
  ]
}
```

**Expected:**
```
"node": {
  "content": [
    {
      "__typename": "StrapiComponentContentImage"
    },
    {
      "__typename": "StrapiComponentContentText"
    }
  ]
}
```

**Comment by EloB** [comment]
This feature would be so useful!

I imagine the query looks like this if it's correctly structured in Graphql.

```gql
query myQuery() {
  allStrapiPage {
    nodes {
      blocks {
        __typename
        ... on StrapiComponentContentImage {
          someProp1
          someProp2
        }
        ... on StrapiComponentContentText {
          someProp3
          someProp4
        }
      }
    }
  }
}
```

**Comment by tomolenet** [comment]
@EloB You are almost right. The working query inside the strapi graphql backend looks like this:

![image](https://user-images.githubusercontent.com/38924650/71955502-c1187280-31e8-11ea-894e-fe9a9e66f233.png)

I would expect the same behaviour on gatsby graphql.

**Comment by EloB** [comment]
> @EloB You are almost right. The working query inside the strapi graphql backend looks like this:
> 
> ![image](https://user-images.githubusercontent.com/38924650/71955502-c1187280-31e8-11ea-894e-fe9a9e66f233.png)
> 
> I would expect the same behaviour on gatsby graphql.

I meant the gatsby graphql... :)

**Comment by tomolenet** [comment]
Just for information.

**Comment by EloB** [comment]
@tomolenet Thanks! I've was watching your Webinar! Really nice!

**Comment by tomolenet** [comment]
> @tomolenet Thanks! I've was watching your Webinar! Really nice!

I am not a strapi team member. But yeah. Was a very good webinar. :+1:

**Comment by bradleyDouglas** [comment]
Hello

Is there any resolution here yet? The ability to query the different component types would be a huge benefit. I tried using ```gatsby-source-graphql```, while my query groups the data by component, I don't get the benefit of Image Sharp on the Images or any good image data for that matter.

**Comment by tomolenet** [comment]
> Is there any resolution here yet? The ability to query the different component types would be a huge benefit

I currently access the component type which is available in PR https://github.com/strapi/gatsby-source-strapi/pull/99. This is obviously just a workaround and not a final good solution like using fragments f.e.

>  I don't get the benefit of Image Sharp on the Images or any good image data for that matter.

I tried this too and ran into the same problems.

**Comment by bradleyDouglas** [comment]
@tomolenet if you use the code from #99, does the query break if the dynamic zone isn't on that specific content type?

For instance, I am creating a Content Type of Pages. From there, I have created some components that can be added - or not added - to the pages. Within Gatsby, I'm dynamically creating pages and passing the ```ID``` in the context and using a Page template. 

Inside my template, I would like to include all of the components in the query. With fragments, I . know this won't break, but will it break without the use of Fragments? 

The idea would be to have a DynamicZone component that accepts the components as an array and then uses a switch case to render out the proper component.

**Comment by tomolenet** [comment]
That's the way I currently use Fragments. This is a short snippet with my implementation.

For example your strapi instance does have the Content Type `Post` with `content` as dynamic zone including the components:
```
Text { content: String }
Source { title: String, source: String }
ImageWithCaption { image: Image, caption: String }

```

The query in your `gatsby-node.js` looks like:
```
exports.createPages = ({ graphql, actions }) => {
  ...
  return graphql(`
    query LoadData {
      ...
      allStrapiPost(sort: {fields: publishAt, order: DESC}) {
        edges {
          node {
            slug
            title
            summary
            publishAt
            thumbnail {
              name
              id
              publicURL
            }
            categories {
              uid
            }
            content { <-- This  is the dynamic zone 
              component <-- Get component type here
              content <-- field of Text component
              source <-- field of Source component
              caption <-- field of ImageWithCaption component
              title <-- field of Source component
              image { ... } <-- field of ImageWithCaption component
              ...
            }
          }
        }
      }
    }
  `, { limit: 1000 }).then((result) => {
    if (result.errors) {
      throw result.errors;
    }

    result.data.allStrapiPost.edges.forEach((edge) => {    
      createPage({ ..., context: { post: edge.node  });
    });

    ...
```

Now you can write something like this in your template:

```
  return post.content.map((c, i) => {
    switch (c.component) {
      case 'content.text':
        return <ComponentText component={c} />;
      case 'content.imageWithCaption':
        return <ComponentImage component={c} />;
      case 'content.source':
        return <ComponentSource component={c} />;
/>;
      default:
        return <div />;
    }
  });
```

**This is just a workaround. There is no usage of Fragments in this code.**

**Comment by bradleyDouglas** [comment]
@tomolenet Ok, that makes sense. I appreciate you posting this!

**Comment by bradleyDouglas** [comment]
@tomolenet Quick question, I've never installed a PR before. What's that process look like and is there anything I need to do in the Gatsby Config file to make sure it references it properly?

**Comment by tomolenet** [comment]
> @tomolenet Quick question, I've never installed a PR before. What's that process look like and is there anything I need to do in the Gatsby Config file to make sure it references it properly?

The easiest way is probably to use the PR in your `package.json`. Maybe fork the PR in your own repo to make sure your app does not break if the owner of the PR removes the repo for example.

```
  "dependencies": {
    ...
    "gatsby-source-strapi": "git+https://github.com/CMatias/gatsby-source-strapi.git",
    ...
```

**Comment by bradleyDouglas** [comment]
@tomolenet Thanks for this. I went ahead and forked the PR, then added to dependencies like you show, then did an NPM install. No errors when I ran ```gatsby develop```, but I don't see anything when I go to the GraphiQL endpoint. I expected to see allStrapiPage, but that's nowhere to be seen. 

Did I miss something?

**Comment by tomolenet** [comment]
> @tomolenet Thanks for this. I went ahead and forked the PR, then added to dependencies like you show, then did an NPM install. No errors when I ran `gatsby develop`, but I don't see anything when I go to the GraphiQL endpoint. I expected to see allStrapiPage, but that's nowhere to be seen.
> 
> Did I miss something?

Have you configured the plugin as described in the [README](https://github.com/strapi/gatsby-source-strapi)?

**Comment by bradleyDouglas** [comment]
@tomolenet Yup followed it exactly. Before I used the PR, I was just using the main repo. That worked as expected. I could access ```allStrapiPage```, see all the fields in my components (all grouped together of course) and get childImageSharp on the images.

After I installed the PR, nothing was showing. 

Here's where I'm really confused now... 

I uninstalled everything and re-installed the source plugin straight from Strapi (just like in the Read Me). When I did that, I could see everything in the GraphiQL explorer. HOWEVER, this time I didn't get any childImageSharp transformations on the images as I did before...

**Comment by tomolenet** [comment]
@bradleyDouglas Sorry not sure how to help without any repo. The #99 ist working for me.

**Comment by bradleyDouglas** [comment]
@tomolenet I understand. Figured out how to get Gatsby to generate images using the ```gatsby-source-graphql```, which allows me to use Fragments. Thought I'd share:

In my ```gatsby-node.js``` file:

```
exports.createResolvers = async ({
    actions,
    cache,
    createNodeId,
    createResolvers,
    store,
    reporter,
}) => {
    const { createNode } = actions

    await createResolvers({
        STRAPI_UploadFile: {
            imageFile: {
                type: 'File',
                async resolve(source) {
                    let sourceUrl = `YOUR_URL${source.url}`

                    return await createRemoteFileNode({
                        url: sourceUrl,
                        store,
                        cache,
                        createNode,
                        createNodeId,
                        reporter,
                    })
                },
            },
        },
    })
}
```

Also in my node file

```
exports.createPages = async ({ actions, graphql }) => {
    const { data } = await graphql(`
        query {
            strapi {
                pages {
                    id
                    page_title
                    HideFromNav
                }
            }
        }
    `)
    data.strapi.pages.forEach(({ id, page_title, HideFromNav }) => {
        const slug = slugify(page_title.toLowerCase())
        actions.createPage({
            path: slug,
            component: path.resolve('./src/templates/page.js'),
            context: {
                id: id,
            },
        })
    })
}
```

Then, in my ```page.js``` file, my query looks like

```
export const pageQuery = graphql`
    query GET_PAGE($id: ID!) {
        strapi {
            page(id: $id) {
                page_title
                content {
                    ... on STRAPI_ComponentLayoutHero {
                        id
                        image {
                            url
                            imageFile {
                                childImageSharp {
                                    fluid {
                                        ...GatsbyImageSharpFluid
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
`
```

**Comment by dlmitchell81** [comment]
Hi - just wondering if there are any updates on this? I've attempted to use https://github.com/strapi/gatsby-source-strapi/pull/99 as mentioned above and am also using something similar to @bradleyDouglas in that I'm using a `Page` content type with dynamic zones. However when I make the use the above I don't see any reference to `allStrapiPages` or `strapiPage` in the GraphiQL explorer as I do prior to using the PR version. I would be grateful for any advice

**Comment by tomolenet** [comment]
> However when I use the above I don't see any reference to `allStrapiPages` or `strapiPage` in the GraphiQL explorer as I do prior to using the PR version. I would be grateful for any advice

Do you have any repo or log? What does your `gatsby-config` look like?

**Comment by bradleyDouglas** [comment]
@dlmitchell81 Did you see my [comment](https://github.com/strapi/gatsby-source-strapi/issues/93#issuecomment-594842885) above? I ended up using the ```gatsby-source-graphql``` plugin and added that code in my ```gatsby-node.js``` file. This allowed me to transform my images and use the fragment approach in my queries.

**Comment by dlmitchell81** [comment]
@tomolenet @bradleyDouglas thank you very much for getting back to me. I realised I'd overlooked adding `graphql` to the options url in `gatsby-config.js`. It wasn't necessary when using `gatsby-source-strapi` and not immediately obvious from the `gatsby-source-graphql` docs, although in hindsight does make sense. 

So far I've not had any need for the Strapi CLI but realised I had to add this globally to enable me to install the Strapi GraphQL plugin via `strapi install graphql` which makes `http://localhost:1337/graphql` available (was receiving a 404 prior to installing the plugin).

My `gatsby-config.js` now looks like this and I can use fragments in my queries to target specific components in Dynamic Zones:

```javascript
{
	resolve: 'gatsby-source-graphql',
	options: {
		typeName: 'Strapi',
		fieldName: 'strapi',
		url: 'http://localhost:1337/graphql',
	},
}
```

**Comment by janschill** [comment]
Thanks for this thread. I was going insane about the types of the components not being returned.

**Comment by kyuumeitai** [comment]
> Hi - just wondering if there are any updates on this? I've attempted to use #99 as mentioned above and am also using something similar to @bradleyDouglas in that I'm using a `Page` content type with dynamic zones. However when I use the above I don't see any reference to `allStrapiPages` or `strapiPage` in the GraphiQL explorer as I do prior to using the PR version. I would be grateful for any advice

Hi @dlmitchell81 , I was passing through this too with my own fork, it seems that there's no build in forked repo, so, you have two options:

1. You need to run `npm install` inside the `node_modules/gatsby-source-strapi` folder and then `npm run build` 
2. In your own fork, add `prepare: npm run build` in the `scripts` sections of your package.json file, then add it in the project package.json pointing to your github forked repo and install it.

I see that you're using graphql directly, I'll try it 

Thanks all for this thread!

**Comment by evanheisler** [comment]
To get around this and support dynamically loading in components based on the API response, I added a text field called `component` with a default value set to whatever the module is called, then under "Configure the VIew", I remove that field so it can't be edited. 

Bit of a hack, but hopefully it helps someone.

**Comment by parthsdoshi** [comment]
For what it's worth, I think this has been fixed by #146.
From my understanding, the above doesn't change isn't included in a release yet so you'll have to pull the latest master.

**Comment by dostuffthatmatters** [comment]
Still the problem with 0.0.12 but fixed with 1.0.0 alpha.

**Comment by multiwebinc** [comment]
I installed the latest alpha, and I can see it adds a `strapi_component` property containing the dynamic zone component type, however, the `__typename` property is still the same for all components. I'm very new to GraphQL, from what I could find, when creating fragments this is based on the type. How can `strapi_component` be used to query different fields depending on the component type? Wouldn't it make more sense to just leave the `__typename` to what is returned from Strapi instead of modifying it and setting another field?

**Comment by MotaZor94** [comment]
Hi everyone, is there any updates on this one? I see on the new release of gatsby-source-strapi the strapi_component field but I'm still struggling with getting the dynamic content up with the strapi plugin.

**Comment by MotaZor94** [comment]
> Still the problem with 0.0.12 but fixed with 1.0.0 alpha.

How is it fixed? The types are still all the same to me with 1.0.0 alpha.

**Comment by dostuffthatmatters** [comment]
@MotaZor94

> I installed the latest alpha, and I can see it adds a `strapi_component` property containing the dynamic zone component type, however, the `__typename` property is still the same for all components.

You can use the `strapi_component` property.

**Comment by Ortimis** [comment]
@dostuffthatmatters the property 'strapi_component' is not available in v3.4.1
Are there any updates on this one?

**Comment by dostuffthatmatters** [comment]
@Ortimis Check out the http://localhost:8000/___graphql page. There you can see every property that is available for the strapi data

**Comment by Ortimis** [comment]
@dostuffthatmatters thanks for the fast answer and for your remark - however, to my knowledge, there is no property visible in /__graphql that specifies the component type

**Comment by dostuffthatmatters** [comment]
@Ortimis On one project with a dynamic blog I am using:
`gatsby-source-strapi 1.0.0-alpha.0` and `strapi 3.5.4`.

In that alpha of the plugin this property was present. I just noticed that they release a version `1.0.1` - I don't have that running anywhere - it is possible that the property from the alpha did not make it into `1.0.1`, which would be ridiculous.

I did not encounter any issues with `1.0.0-alpha.0` so maybe you could use that.

**Comment by remidej** [comment]
I'm closing this issue, as it only concerns the way the plugin handled dynamic zones before the stable v1 release.

The stable v1 relies on the JSON type for dynamic zones, precisely to avoid these typing issues. It's a different tradeoff that has other drawbacks, but we've chosen to keep it for now, until we can rewrite the plugin in a future major version. I've detailed our choice there: https://github.com/strapi/gatsby-source-strapi/issues/191#issuecomment-846007145

---

> it is possible that the property from the alpha did not make it into 1.0.1, which would be ridiculous

@dostuffthatmatters we do our best to follow semver, but experimental releases can bring breaking changes. So make sure to read the changelog when you try an alpha or a beta
